### ISSUE TITLE
Shouldn't the library include babel/polyfill

### ISSUE THREAD

**Issue by pankajpatel** [modulor-js/modulor-html#34]
https://github.com/modulor-js/modulor-html/blob/a85abb3d256032e4164fdabee93086587fc63311/.babelrc#L3

Should we include babel/polyfill or core-js to support old browsers?

**Comment by nogizhopaboroda** [comment]
It probably makes more sense to use babel env-preset https://babeljs.io/docs/en/babel-preset-env/
But there's really nothing to transpile with babel/polyfill or core-js except for `Map`, which is supported even by ie10

**Comment by pankajpatel** [comment]
It will never hurt to have polyfill for `Map` as it is throwing in following context:
<img width="1113" alt="error" src="https://user-images.githubusercontent.com/251937/43765301-e3a1e540-9a2f-11e8-8274-91e843e1e8ec.png">

**Comment by nogizhopaboroda** [comment]
Adding polyfills increases the bundle size. 

Wait, is it really v32 (latest one is 68) or bugsnag looked it up incorrectly? I think map polyfill is not enough here and some array methods need to be polyfilled too. We can have additional bundle and call it something like `old-browsers.js` or so. But it definitely shouldn't be in the main build, because small size is one of the goals.

Another way could be to handle this case on your app level (e.g. webpack ProvidePlugin or so)

But seriously, even ie10 (which is officially not supported for several years already) has map =)

**Comment by pankajpatel** [comment]
Makes sense to handle at application level. Thanks.
